@startuml


class utilisateurs{
consulter_données_indicateurs_publics()
consulter_etude_de_cas()
exporter()
visualiser()
}


class utilisateur_compte{
id
login
mot_de_passe
se_connecter()
modifier_droits_accès()
modifier_mdp()
}

class travailleur{
age
sexe
éducation enum
}

class décideur_projet{
politique()
suivre()
evaluer()
}


class coop_org_prod{
consulter_données_indicateurs_coop()
}


class technicien{
saisir()
}

class producteur{
SIRET
consulter_données_privées()
saisir()
}

class chercheur{
vérifier_bien_chercheur
}

class étude{
Zone_géographique
}

class exploitation{
zone
nom
adresse
}

class parcelle{
culture
itinéraire_technique
}

class projet{
objectif
budget
durée
}

class Zone_géographique << (D,#FF7700) DataType>> {
  nom: String
  type ENUM{département, agroécosystème, ...}
}


class Adresse << (D,#FF7700) DataType>> {
  numéro
  rue
  ville
  pays
 }



décideur_projet "*"--"*" projet : créer >
producteur "1"--"1" exploitation: posséder >
technicien "*"--"*" exploitation: gérer >
producteur o--"1" coop_org_prod
exploitation "1"--* parcelle
étude "1"--"1" chercheur : rédiger <
producteur "*"-"*" étude : participer >

utilisateurs <|-- utilisateur_compte
utilisateur_compte <|-- décideur_projet
utilisateur_compte <|-- coop_org_prod
utilisateur_compte <|-- technicien
utilisateur_compte <|-- producteur
travailleur <|-- producteur
utilisateur_compte <|-- chercheur
travailleur "*"--"*" exploitation  : travailler

projet -- étude : se_base_sur???


enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml